import React, { useState, useEffect } from 'react';
import { apiRequest } from '../services/api.js';

export function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showGenerateModal, setShowGenerateModal] = useState(false);

  const [form, setForm] = useState({
    title: '',
    reportType: 'CAMERA_HEALTH',
    format: 'CSV'
  });

  useEffect(() => {
    loadReports();
  }, []);

  async function loadReports() {
    setLoading(true);
    try {
      const res = await apiRequest('/reports');
      if (res.success && res.data) {
        setReports(res.data.items || []);
      }
    } catch (err) {
      console.error('Failed to load reports:', err.message);
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate(e) {
    e.preventDefault();
    try {
      const res = await apiRequest('/reports', {
        method: 'POST',
        body: form
      });
      if (res.success) {
        alert('Report generation job queued asynchronously.');
        setShowGenerateModal(false);
        setForm({ title: '', reportType: 'CAMERA_HEALTH', format: 'CSV' });
        setTimeout(loadReports, 1000);
      }
    } catch (err) {
      alert(`Report request failed: ${err.message}`);
    }
  }

  function handleDownload(reportId, title, format) {
    const token = localStorage.getItem('gov_auth_token');
    fetch(`/api/reports/${reportId}/download`, {
      headers: { Authorization: `Bearer ${token}` }
    })
      .then((res) => {
        if (!res.ok) throw new Error('Download failed');
        return res.blob();
      })
      .then((blob) => {
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${title.replace(/\s+/g, '_')}.${format.toLowerCase()}`;
        document.body.appendChild(a);
        a.click();
        a.remove();
      })
      .catch((err) => alert(err.message));
  }

  return (
    <div>
      <div className="breadcrumbs">Home / Operational Reporting</div>
      <div className="page-header">
        <div>
          <h1>Government Operational Reporting</h1>
          <p style={{ color: 'var(--text-light)', fontSize: '12.5px', marginTop: 2 }}>
            Asynchronous report generator for camera availability, ANPR intelligence logs, alerts, and investigations.
          </p>
        </div>
        <button className="btn btn-primary" onClick={() => setShowGenerateModal(true)}>
          + Generate New Report
        </button>
      </div>

      <div className="panel">
        <div className="panel-header">
          <h2>Generated Reports History</h2>
          <button className="btn btn-secondary btn-sm" onClick={loadReports}>Refresh Queue</button>
        </div>
        <div className="data-table-wrapper">
          <table className="gov-table">
            <thead>
              <tr>
                <th>Report Title</th>
                <th>Category</th>
                <th>Format</th>
                <th>Generated By</th>
                <th>Queued Date</th>
                <th>Status</th>
                <th>Download</th>
              </tr>
            </thead>
            <tbody>
              {reports.length === 0 ? (
                <tr>
                  <td colSpan="7" style={{ textAlign: 'center', padding: 24, color: 'var(--text-light)' }}>
                    {loading ? 'Loading report jobs...' : 'No reports generated yet.'}
                  </td>
                </tr>
              ) : (
                reports.map((r) => (
                  <tr key={r.id}>
                    <td><strong>{r.title}</strong></td>
                    <td>{r.reportType}</td>
                    <td><span className="badge badge-connecting">{r.format}</span></td>
                    <td>{r.createdByName}</td>
                    <td style={{ fontSize: '11.5px', whiteSpace: 'nowrap' }}>
                      {new Date(r.createdAt).toLocaleString()}
                    </td>
                    <td>
                      <span className={`badge badge-${r.status.toLowerCase()}`}>
                        {r.status}
                      </span>
                    </td>
                    <td>
                      {r.status === 'COMPLETED' ? (
                        <button
                          className="btn btn-primary btn-sm"
                          onClick={() => handleDownload(r.id, r.title, r.format)}
                        >
                          Download {r.format}
                        </button>
                      ) : (
                        <span style={{ fontSize: '11px', color: 'var(--text-light)' }}>Processing...</span>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Generate Report Modal */}
      {showGenerateModal && (
        <div className="modal-backdrop">
          <div className="modal-content">
            <div className="modal-header">
              <h3>Request Asynchronous Report Generation</h3>
              <button className="modal-close" onClick={() => setShowGenerateModal(false)}>&times;</button>
            </div>
            <form onSubmit={handleGenerate}>
              <div className="modal-body">
                <div className="form-group">
                  <label>Report Title *</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Gujarat State Camera Availability & Health Audit"
                    value={form.title}
                    onChange={(e) => setForm({ ...form, title: e.target.value })}
                  />
                </div>
                <div className="form-group">
                  <label>Report Category *</label>
                  <select
                    value={form.reportType}
                    onChange={(e) => setForm({ ...form, reportType: e.target.value })}
                  >
                    <option value="CAMERA_HEALTH">Camera Asset Status & Health Report</option>
                    <option value="DETECTION_ANPR">ANPR License Plate Detections Log</option>
                    <option value="ALERTS_SUMMARY">Surveillance Alerts Summary Report</option>
                    <option value="INVESTIGATIONS_SUMMARY">Active Investigations Dossier Report</option>
                    <option value="AUDIT_TRAIL">System Security & Access Audit Trail</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Output Export Format *</label>
                  <select
                    value={form.format}
                    onChange={(e) => setForm({ ...form, format: e.target.value })}
                  >
                    <option value="CSV">Comma Separated Values (.CSV)</option>
                    <option value="JSON">Structured JSON (.JSON)</option>
                  </select>
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setShowGenerateModal(false)}>Cancel</button>
                <button type="submit" className="btn btn-primary">Queue Report Generation</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
